### ISSUE TITLE
Added status categorization

### ISSUE THREAD

**Issue by Stardog** [AppStateESS/systemsinventory#11]
Each device should have a status:

- Processing - received from vendor, building system
- Assigned - given to user
- Storage - in the office for reassignment
- Surplus - sent to surplus

A device should have a life cycle of processing to assigned to storage to assigned to surplus.

Searching by status should be on the list.

**Comment by eberhardtm** [comment]
Maybe just need 2 types of storage instead of processing.
1. In storage new(New device that just came in from an order.)
2. In storage used (Used device that can now be reassigned to a new user).
